server {
    listen 8080;

    location /api/ {
        proxy_pass http://${BACKEND_HOST}/;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
