apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-demo
  namespace: troubleshoot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-demo
  template:
    metadata:
      labels:
        app: imagepull-demo
    spec:
      containers:
        - name: app
          image: nginx:this-tag-does-not-exist
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 64Mi
