apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-fail-demo
  namespace: troubleshoot-demo
  labels:
    app: readiness-fail-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-fail-demo
  template:
    metadata:
      labels:
        app: readiness-fail-demo
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /doesnotexist
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 2
